/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.InlineResponse20011ResultContentWinners = factory(root.ApChallengeMicroservice.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The InlineResponse20011ResultContentWinners model module.
   * @module model/InlineResponse20011ResultContentWinners
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>InlineResponse20011ResultContentWinners</code>.
   * @alias module:model/InlineResponse20011ResultContentWinners
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>InlineResponse20011ResultContentWinners</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20011ResultContentWinners} obj Optional instance to populate.
   * @return {module:model/InlineResponse20011ResultContentWinners} The populated <code>InlineResponse20011ResultContentWinners</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('submissionId'))
        obj.submissionId = ApiClient.convertToType(data['submissionId'], 'Number');
      if (data.hasOwnProperty('submitter'))
        obj.submitter = ApiClient.convertToType(data['submitter'], 'String');
      if (data.hasOwnProperty('submissionTime'))
        obj.submissionTime = ApiClient.convertToType(data['submissionTime'], 'Date');
      if (data.hasOwnProperty('rank'))
        obj.rank = ApiClient.convertToType(data['rank'], 'Number');
      if (data.hasOwnProperty('points'))
        obj.points = ApiClient.convertToType(data['points'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} submissionId
   */
  exports.prototype.submissionId = undefined;

  /**
   * @member {String} submitter
   */
  exports.prototype.submitter = undefined;

  /**
   * @member {Date} submissionTime
   */
  exports.prototype.submissionTime = undefined;

  /**
   * @member {Number} rank
   */
  exports.prototype.rank = undefined;

  /**
   * @member {Number} points
   */
  exports.prototype.points = undefined;

  return exports;

}));
