/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.InlineResponse20011ResultContentRegistrants = factory(root.ApChallengeMicroservice.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The InlineResponse20011ResultContentRegistrants model module.
   * @module model/InlineResponse20011ResultContentRegistrants
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>InlineResponse20011ResultContentRegistrants</code>.
   * @alias module:model/InlineResponse20011ResultContentRegistrants
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>InlineResponse20011ResultContentRegistrants</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20011ResultContentRegistrants} obj Optional instance to populate.
   * @return {module:model/InlineResponse20011ResultContentRegistrants} The populated <code>InlineResponse20011ResultContentRegistrants</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('submissionDate'))
        obj.submissionDate = ApiClient.convertToType(data['submissionDate'], 'Date');
      if (data.hasOwnProperty('reliability'))
        obj.reliability = ApiClient.convertToType(data['reliability'], 'Number');
      if (data.hasOwnProperty('colorStyle'))
        obj.colorStyle = ApiClient.convertToType(data['colorStyle'], 'String');
      if (data.hasOwnProperty('handle'))
        obj.handle = ApiClient.convertToType(data['handle'], 'String');
      if (data.hasOwnProperty('rating'))
        obj.rating = ApiClient.convertToType(data['rating'], 'Number');
      if (data.hasOwnProperty('registrationDate'))
        obj.registrationDate = ApiClient.convertToType(data['registrationDate'], 'Date');
    }
    return obj;
  }

  /**
   * @member {Date} submissionDate
   */
  exports.prototype.submissionDate = undefined;

  /**
   * @member {Number} reliability
   */
  exports.prototype.reliability = undefined;

  /**
   * @member {String} colorStyle
   */
  exports.prototype.colorStyle = undefined;

  /**
   * @member {String} handle
   */
  exports.prototype.handle = undefined;

  /**
   * @member {Number} rating
   */
  exports.prototype.rating = undefined;

  /**
   * @member {Date} registrationDate
   */
  exports.prototype.registrationDate = undefined;

  return exports;

}));
