/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.InlineResponse200ResultWinners = factory(root.ApChallengeMicroservice.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The InlineResponse200ResultWinners model module.
   * @module model/InlineResponse200ResultWinners
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>InlineResponse200ResultWinners</code>.
   * @alias module:model/InlineResponse200ResultWinners
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>InlineResponse200ResultWinners</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse200ResultWinners} obj Optional instance to populate.
   * @return {module:model/InlineResponse200ResultWinners} The populated <code>InlineResponse200ResultWinners</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('handle'))
        obj.handle = ApiClient.convertToType(data['handle'], 'String');
      if (data.hasOwnProperty('placement'))
        obj.placement = ApiClient.convertToType(data['placement'], 'Number');
    }
    return obj;
  }

  /**
   * the winner user id
   * @member {Number} userId
   */
  exports.prototype.userId = undefined;

  /**
   * the winning type, can be either checkpoint or final
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * the winner handle
   * @member {String} handle
   */
  exports.prototype.handle = undefined;

  /**
   * the winner placement
   * @member {Number} placement
   */
  exports.prototype.placement = undefined;

  return exports;

}));
