/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.InlineResponse20010ResultUserMMDetails = factory(root.ApChallengeMicroservice.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The InlineResponse20010ResultUserMMDetails model module.
   * @module model/InlineResponse20010ResultUserMMDetails
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>InlineResponse20010ResultUserMMDetails</code>.
   * @alias module:model/InlineResponse20010ResultUserMMDetails
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>InlineResponse20010ResultUserMMDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20010ResultUserMMDetails} obj Optional instance to populate.
   * @return {module:model/InlineResponse20010ResultUserMMDetails} The populated <code>InlineResponse20010ResultUserMMDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('contestId'))
        obj.contestId = ApiClient.convertToType(data['contestId'], 'Number');
      if (data.hasOwnProperty('roundId'))
        obj.roundId = ApiClient.convertToType(data['roundId'], 'Number');
      if (data.hasOwnProperty('oldRating'))
        obj.oldRating = ApiClient.convertToType(data['oldRating'], 'Number');
      if (data.hasOwnProperty('newRating'))
        obj.newRating = ApiClient.convertToType(data['newRating'], 'Number');
      if (data.hasOwnProperty('rated'))
        obj.rated = ApiClient.convertToType(data['rated'], 'Number');
      if (data.hasOwnProperty('pointTotal'))
        obj.pointTotal = ApiClient.convertToType(data['pointTotal'], 'Number');
      if (data.hasOwnProperty('ovarallRank'))
        obj.ovarallRank = ApiClient.convertToType(data['ovarallRank'], 'Number');
      if (data.hasOwnProperty('numSubmissions'))
        obj.numSubmissions = ApiClient.convertToType(data['numSubmissions'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} contestId
   */
  exports.prototype.contestId = undefined;

  /**
   * @member {Number} roundId
   */
  exports.prototype.roundId = undefined;

  /**
   * @member {Number} oldRating
   */
  exports.prototype.oldRating = undefined;

  /**
   * @member {Number} newRating
   */
  exports.prototype.newRating = undefined;

  /**
   * @member {Number} rated
   */
  exports.prototype.rated = undefined;

  /**
   * @member {Number} pointTotal
   */
  exports.prototype.pointTotal = undefined;

  /**
   * @member {Number} ovarallRank
   */
  exports.prototype.ovarallRank = undefined;

  /**
   * @member {Number} numSubmissions
   */
  exports.prototype.numSubmissions = undefined;

  return exports;

}));
