/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse20011ResultContentSubmissions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse20011ResultContentSubmissions'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.InlineResponse20011ResultContentSubmissions1 = factory(root.ApChallengeMicroservice.ApiClient, root.ApChallengeMicroservice.InlineResponse20011ResultContentSubmissions);
  }
}(this, function(ApiClient, InlineResponse20011ResultContentSubmissions) {
  'use strict';

  /**
   * The InlineResponse20011ResultContentSubmissions1 model module.
   * @module model/InlineResponse20011ResultContentSubmissions1
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>InlineResponse20011ResultContentSubmissions1</code>.
   * @alias module:model/InlineResponse20011ResultContentSubmissions1
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>InlineResponse20011ResultContentSubmissions1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20011ResultContentSubmissions1} obj Optional instance to populate.
   * @return {module:model/InlineResponse20011ResultContentSubmissions1} The populated <code>InlineResponse20011ResultContentSubmissions1</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('submitterId'))
        obj.submitterId = ApiClient.convertToType(data['submitterId'], 'Number');
      if (data.hasOwnProperty('submitter'))
        obj.submitter = ApiClient.convertToType(data['submitter'], 'String');
      if (data.hasOwnProperty('submissions'))
        obj.submissions = ApiClient.convertToType(data['submissions'], [InlineResponse20011ResultContentSubmissions]);
    }
    return obj;
  }

  /**
   * @member {Number} submitterId
   */
  exports.prototype.submitterId = undefined;

  /**
   * @member {String} submitter
   */
  exports.prototype.submitter = undefined;

  /**
   * @member {Array.<module:model/InlineResponse20011ResultContentSubmissions>} submissions
   */
  exports.prototype.submissions = undefined;

  return exports;

}));
