/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ResponseMetadataFields'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ResponseMetadataFields'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.ResponseMetadata = factory(root.ApChallengeMicroservice.ApiClient, root.ApChallengeMicroservice.ResponseMetadataFields);
  }
}(this, function(ApiClient, ResponseMetadataFields) {
  'use strict';

  /**
   * The ResponseMetadata model module.
   * @module model/ResponseMetadata
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>ResponseMetadata</code>.
   * @alias module:model/ResponseMetadata
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ResponseMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponseMetadata} obj Optional instance to populate.
   * @return {module:model/ResponseMetadata} The populated <code>ResponseMetadata</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('totalCount'))
        obj.totalCount = ApiClient.convertToType(data['totalCount'], 'Number');
      if (data.hasOwnProperty('fields'))
        obj.fields = ResponseMetadataFields.constructFromObject(data['fields']);
    }
    return obj;
  }

  /**
   * Total count of the objects
   * @member {Number} totalCount
   */
  exports.prototype.totalCount = undefined;

  /**
   * @member {module:model/ResponseMetadataFields} fields
   */
  exports.prototype.fields = undefined;

  return exports;

}));
