/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChallengeUpdate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChallengeUpdate'));
  } else {
    // Browser globals (root is window)
    if (!root.ApChallengeMicroservice) {
      root.ApChallengeMicroservice = {};
    }
    root.ApChallengeMicroservice.UpdateChallengeBodyParam = factory(root.ApChallengeMicroservice.ApiClient, root.ApChallengeMicroservice.ChallengeUpdate);
  }
}(this, function(ApiClient, ChallengeUpdate) {
  'use strict';

  /**
   * The UpdateChallengeBodyParam model module.
   * @module model/UpdateChallengeBodyParam
   * @version 1.0.5
   */

  /**
   * Constructs a new <code>UpdateChallengeBodyParam</code>.
   * @alias module:model/UpdateChallengeBodyParam
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UpdateChallengeBodyParam</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateChallengeBodyParam} obj Optional instance to populate.
   * @return {module:model/UpdateChallengeBodyParam} The populated <code>UpdateChallengeBodyParam</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('param'))
        obj.param = ChallengeUpdate.constructFromObject(data['param']);
    }
    return obj;
  }

  /**
   * @member {module:model/ChallengeUpdate} param
   */
  exports.prototype.param = undefined;

  return exports;

}));
