/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AddResourceBody', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.AddResourceBody();
      });

      it('should create an instance of AddResourceBody', function() {
        // TODO: update the code to test AddResourceBody
        expect(instance).to.be.a(ApChallengeMicroservice.AddResourceBody);
      });

      it('should have the property roleId (base name: "roleId")', function() {
        // TODO: update the code to test the property roleId
        expect(instance).to.have.property('roleId');
        // expect(instance.roleId).to.be(expectedValueLiteral);
      });

      it('should have the property resourceUserId (base name: "resourceUserId")', function() {
        // TODO: update the code to test the property resourceUserId
        expect(instance).to.have.property('resourceUserId');
        // expect(instance.resourceUserId).to.be(expectedValueLiteral);
      });

      it('should have the property phaseId (base name: "phaseId")', function() {
        // TODO: update the code to test the property phaseId
        expect(instance).to.have.property('phaseId');
        // expect(instance.phaseId).to.be(expectedValueLiteral);
      });

      it('should have the property addNotification (base name: "addNotification")', function() {
        // TODO: update the code to test the property addNotification
        expect(instance).to.have.property('addNotification');
        // expect(instance.addNotification).to.be(expectedValueLiteral);
      });

      it('should have the property addForumWatch (base name: "addForumWatch")', function() {
        // TODO: update the code to test the property addForumWatch
        expect(instance).to.have.property('addForumWatch');
        // expect(instance.addForumWatch).to.be(expectedValueLiteral);
      });

      it('should have the property isStudio (base name: "isStudio")', function() {
        // TODO: update the code to test the property isStudio
        expect(instance).to.have.property('isStudio');
        // expect(instance.isStudio).to.be(expectedValueLiteral);
      });

      it('should have the property checkTerm (base name: "checkTerm")', function() {
        // TODO: update the code to test the property checkTerm
        expect(instance).to.have.property('checkTerm');
        // expect(instance.checkTerm).to.be(expectedValueLiteral);
      });

    });
  });

}));
