/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DirectPrize', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.DirectPrize();
      });

      it('should create an instance of DirectPrize', function() {
        // TODO: update the code to test DirectPrize
        expect(instance).to.be.a(ApChallengeMicroservice.DirectPrize);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property placement (base name: "placement")', function() {
        // TODO: update the code to test the property placement
        expect(instance).to.have.property('placement');
        // expect(instance.placement).to.be(expectedValueLiteral);
      });

      it('should have the property prizeAmount (base name: "prizeAmount")', function() {
        // TODO: update the code to test the property prizeAmount
        expect(instance).to.have.property('prizeAmount');
        // expect(instance.prizeAmount).to.be(expectedValueLiteral);
      });

      it('should have the property prizeType (base name: "prizeType")', function() {
        // TODO: update the code to test the property prizeType
        expect(instance).to.have.property('prizeType');
        // expect(instance.prizeType).to.be(expectedValueLiteral);
      });

      it('should have the property challengeId (base name: "challengeId")', function() {
        // TODO: update the code to test the property challengeId
        expect(instance).to.have.property('challengeId');
        // expect(instance.challengeId).to.be(expectedValueLiteral);
      });

    });
  });

}));
