/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse20011ResultContentSubmissions1', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.InlineResponse20011ResultContentSubmissions1();
      });

      it('should create an instance of InlineResponse20011ResultContentSubmissions1', function() {
        // TODO: update the code to test InlineResponse20011ResultContentSubmissions1
        expect(instance).to.be.a(ApChallengeMicroservice.InlineResponse20011ResultContentSubmissions1);
      });

      it('should have the property submitterId (base name: "submitterId")', function() {
        // TODO: update the code to test the property submitterId
        expect(instance).to.have.property('submitterId');
        // expect(instance.submitterId).to.be(expectedValueLiteral);
      });

      it('should have the property submitter (base name: "submitter")', function() {
        // TODO: update the code to test the property submitter
        expect(instance).to.have.property('submitter');
        // expect(instance.submitter).to.be(expectedValueLiteral);
      });

      it('should have the property submissions (base name: "submissions")', function() {
        // TODO: update the code to test the property submissions
        expect(instance).to.have.property('submissions');
        // expect(instance.submissions).to.be(expectedValueLiteral);
      });

    });
  });

}));
