/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse20013ResultContent', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.InlineResponse20013ResultContent();
      });

      it('should create an instance of InlineResponse20013ResultContent', function() {
        // TODO: update the code to test InlineResponse20013ResultContent
        expect(instance).to.be.a(ApChallengeMicroservice.InlineResponse20013ResultContent);
      });

      it('should have the property contestId (base name: "contestId")', function() {
        // TODO: update the code to test the property contestId
        expect(instance).to.have.property('contestId');
        // expect(instance.contestId).to.be(expectedValueLiteral);
      });

      it('should have the property componentId (base name: "componentId")', function() {
        // TODO: update the code to test the property componentId
        expect(instance).to.have.property('componentId');
        // expect(instance.componentId).to.be(expectedValueLiteral);
      });

      it('should have the property roundId (base name: "roundId")', function() {
        // TODO: update the code to test the property roundId
        expect(instance).to.have.property('roundId');
        // expect(instance.roundId).to.be(expectedValueLiteral);
      });

      it('should have the property isRegistered (base name: "isRegistered")', function() {
        // TODO: update the code to test the property isRegistered
        expect(instance).to.have.property('isRegistered');
        // expect(instance.isRegistered).to.be(expectedValueLiteral);
      });

    });
  });

}));
