/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse200ResultSubmissions', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.InlineResponse200ResultSubmissions();
      });

      it('should create an instance of InlineResponse200ResultSubmissions', function() {
        // TODO: update the code to test InlineResponse200ResultSubmissions
        expect(instance).to.be.a(ApChallengeMicroservice.InlineResponse200ResultSubmissions);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property score (base name: "score")', function() {
        // TODO: update the code to test the property score
        expect(instance).to.have.property('score');
        // expect(instance.score).to.be(expectedValueLiteral);
      });

      it('should have the property placement (base name: "placement")', function() {
        // TODO: update the code to test the property placement
        expect(instance).to.have.property('placement');
        // expect(instance.placement).to.be(expectedValueLiteral);
      });

      it('should have the property challengeId (base name: "challengeId")', function() {
        // TODO: update the code to test the property challengeId
        expect(instance).to.have.property('challengeId');
        // expect(instance.challengeId).to.be(expectedValueLiteral);
      });

      it('should have the property submissionImage (base name: "submissionImage")', function() {
        // TODO: update the code to test the property submissionImage
        expect(instance).to.have.property('submissionImage');
        // expect(instance.submissionImage).to.be(expectedValueLiteral);
      });

      it('should have the property submittedAt (base name: "submittedAt")', function() {
        // TODO: update the code to test the property submittedAt
        expect(instance).to.have.property('submittedAt');
        // expect(instance.submittedAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
