/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse20014ResultContent', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.InlineResponse20014ResultContent();
      });

      it('should create an instance of InlineResponse20014ResultContent', function() {
        // TODO: update the code to test InlineResponse20014ResultContent
        expect(instance).to.be.a(ApChallengeMicroservice.InlineResponse20014ResultContent);
      });

      it('should have the property myChallengesCount (base name: "myChallengesCount")', function() {
        // TODO: update the code to test the property myChallengesCount
        expect(instance).to.have.property('myChallengesCount');
        // expect(instance.myChallengesCount).to.be(expectedValueLiteral);
      });

      it('should have the property openChallengesCount (base name: "openChallengesCount")', function() {
        // TODO: update the code to test the property openChallengesCount
        expect(instance).to.have.property('openChallengesCount');
        // expect(instance.openChallengesCount).to.be(expectedValueLiteral);
      });

      it('should have the property ongoingChallengesCount (base name: "ongoingChallengesCount")', function() {
        // TODO: update the code to test the property ongoingChallengesCount
        expect(instance).to.have.property('ongoingChallengesCount');
        // expect(instance.ongoingChallengesCount).to.be(expectedValueLiteral);
      });

      it('should have the property allChallengesCount (base name: "allChallengesCount")', function() {
        // TODO: update the code to test the property allChallengesCount
        expect(instance).to.have.property('allChallengesCount');
        // expect(instance.allChallengesCount).to.be(expectedValueLiteral);
      });

    });
  });

}));
