/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2007ResultContent', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.InlineResponse2007ResultContent();
      });

      it('should create an instance of InlineResponse2007ResultContent', function() {
        // TODO: update the code to test InlineResponse2007ResultContent
        expect(instance).to.be.a(ApChallengeMicroservice.InlineResponse2007ResultContent);
      });

      it('should have the property userId (base name: "userId")', function() {
        // TODO: update the code to test the property userId
        expect(instance).to.have.property('userId');
        // expect(instance.userId).to.be(expectedValueLiteral);
      });

      it('should have the property oldRating (base name: "oldRating")', function() {
        // TODO: update the code to test the property oldRating
        expect(instance).to.have.property('oldRating');
        // expect(instance.oldRating).to.be(expectedValueLiteral);
      });

      it('should have the property newRating (base name: "newRating")', function() {
        // TODO: update the code to test the property newRating
        expect(instance).to.have.property('newRating');
        // expect(instance.newRating).to.be(expectedValueLiteral);
      });

      it('should have the property rated (base name: "rated")', function() {
        // TODO: update the code to test the property rated
        expect(instance).to.have.property('rated');
        // expect(instance.rated).to.be(expectedValueLiteral);
      });

      it('should have the property roomPlacement (base name: "roomPlacement")', function() {
        // TODO: update the code to test the property roomPlacement
        expect(instance).to.have.property('roomPlacement');
        // expect(instance.roomPlacement).to.be(expectedValueLiteral);
      });

      it('should have the property division (base name: "division")', function() {
        // TODO: update the code to test the property division
        expect(instance).to.have.property('division');
        // expect(instance.division).to.be(expectedValueLiteral);
      });

      it('should have the property finalPoints (base name: "finalPoints")', function() {
        // TODO: update the code to test the property finalPoints
        expect(instance).to.have.property('finalPoints');
        // expect(instance.finalPoints).to.be(expectedValueLiteral);
      });

      it('should have the property divisionPlacement (base name: "divisionPlacement")', function() {
        // TODO: update the code to test the property divisionPlacement
        expect(instance).to.have.property('divisionPlacement');
        // expect(instance.divisionPlacement).to.be(expectedValueLiteral);
      });

      it('should have the property overallRank (base name: "overallRank")', function() {
        // TODO: update the code to test the property overallRank
        expect(instance).to.have.property('overallRank');
        // expect(instance.overallRank).to.be(expectedValueLiteral);
      });

      it('should have the property contestId (base name: "contestId")', function() {
        // TODO: update the code to test the property contestId
        expect(instance).to.have.property('contestId');
        // expect(instance.contestId).to.be(expectedValueLiteral);
      });

    });
  });

}));
