/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse20011ResultContentRegistrants', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.InlineResponse20011ResultContentRegistrants();
      });

      it('should create an instance of InlineResponse20011ResultContentRegistrants', function() {
        // TODO: update the code to test InlineResponse20011ResultContentRegistrants
        expect(instance).to.be.a(ApChallengeMicroservice.InlineResponse20011ResultContentRegistrants);
      });

      it('should have the property submissionDate (base name: "submissionDate")', function() {
        // TODO: update the code to test the property submissionDate
        expect(instance).to.have.property('submissionDate');
        // expect(instance.submissionDate).to.be(expectedValueLiteral);
      });

      it('should have the property reliability (base name: "reliability")', function() {
        // TODO: update the code to test the property reliability
        expect(instance).to.have.property('reliability');
        // expect(instance.reliability).to.be(expectedValueLiteral);
      });

      it('should have the property colorStyle (base name: "colorStyle")', function() {
        // TODO: update the code to test the property colorStyle
        expect(instance).to.have.property('colorStyle');
        // expect(instance.colorStyle).to.be(expectedValueLiteral);
      });

      it('should have the property handle (base name: "handle")', function() {
        // TODO: update the code to test the property handle
        expect(instance).to.have.property('handle');
        // expect(instance.handle).to.be(expectedValueLiteral);
      });

      it('should have the property rating (base name: "rating")', function() {
        // TODO: update the code to test the property rating
        expect(instance).to.have.property('rating');
        // expect(instance.rating).to.be(expectedValueLiteral);
      });

      it('should have the property registrationDate (base name: "registrationDate")', function() {
        // TODO: update the code to test the property registrationDate
        expect(instance).to.have.property('registrationDate');
        // expect(instance.registrationDate).to.be(expectedValueLiteral);
      });

    });
  });

}));
