/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2003ResultContent', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.InlineResponse2003ResultContent();
      });

      it('should create an instance of InlineResponse2003ResultContent', function() {
        // TODO: update the code to test InlineResponse2003ResultContent
        expect(instance).to.be.a(ApChallengeMicroservice.InlineResponse2003ResultContent);
      });

      it('should have the property phaseType (base name: "phaseType")', function() {
        // TODO: update the code to test the property phaseType
        expect(instance).to.have.property('phaseType');
        // expect(instance.phaseType).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property fixedStarTime (base name: "fixedStarTime")', function() {
        // TODO: update the code to test the property fixedStarTime
        expect(instance).to.have.property('fixedStarTime');
        // expect(instance.fixedStarTime).to.be(expectedValueLiteral);
      });

      it('should have the property scheduledStarTime (base name: "scheduledStarTime")', function() {
        // TODO: update the code to test the property scheduledStarTime
        expect(instance).to.have.property('scheduledStarTime');
        // expect(instance.scheduledStarTime).to.be(expectedValueLiteral);
      });

      it('should have the property scheduledEndTime (base name: "scheduledEndTime")', function() {
        // TODO: update the code to test the property scheduledEndTime
        expect(instance).to.have.property('scheduledEndTime');
        // expect(instance.scheduledEndTime).to.be(expectedValueLiteral);
      });

      it('should have the property actualStartTime (base name: "actualStartTime")', function() {
        // TODO: update the code to test the property actualStartTime
        expect(instance).to.have.property('actualStartTime');
        // expect(instance.actualStartTime).to.be(expectedValueLiteral);
      });

      it('should have the property actualEndTime (base name: "actualEndTime")', function() {
        // TODO: update the code to test the property actualEndTime
        expect(instance).to.have.property('actualEndTime');
        // expect(instance.actualEndTime).to.be(expectedValueLiteral);
      });

      it('should have the property duration (base name: "duration")', function() {
        // TODO: update the code to test the property duration
        expect(instance).to.have.property('duration');
        // expect(instance.duration).to.be(expectedValueLiteral);
      });

    });
  });

}));
