/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse20012Results', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.InlineResponse20012Results();
      });

      it('should create an instance of InlineResponse20012Results', function() {
        // TODO: update the code to test InlineResponse20012Results
        expect(instance).to.be.a(ApChallengeMicroservice.InlineResponse20012Results);
      });

      it('should have the property handle (base name: "handle")', function() {
        // TODO: update the code to test the property handle
        expect(instance).to.have.property('handle');
        // expect(instance.handle).to.be(expectedValueLiteral);
      });

      it('should have the property placement (base name: "placement")', function() {
        // TODO: update the code to test the property placement
        expect(instance).to.have.property('placement');
        // expect(instance.placement).to.be(expectedValueLiteral);
      });

      it('should have the property submissionDate (base name: "submissionDate")', function() {
        // TODO: update the code to test the property submissionDate
        expect(instance).to.have.property('submissionDate');
        // expect(instance.submissionDate).to.be(expectedValueLiteral);
      });

      it('should have the property submissionStatus (base name: "submissionStatus")', function() {
        // TODO: update the code to test the property submissionStatus
        expect(instance).to.have.property('submissionStatus');
        // expect(instance.submissionStatus).to.be(expectedValueLiteral);
      });

      it('should have the property registrationDate (base name: "registrationDate")', function() {
        // TODO: update the code to test the property registrationDate
        expect(instance).to.have.property('registrationDate');
        // expect(instance.registrationDate).to.be(expectedValueLiteral);
      });

      it('should have the property points (base name: "points")', function() {
        // TODO: update the code to test the property points
        expect(instance).to.have.property('points');
        // expect(instance.points).to.be(expectedValueLiteral);
      });

      it('should have the property finalScore (base name: "finalScore")', function() {
        // TODO: update the code to test the property finalScore
        expect(instance).to.have.property('finalScore');
        // expect(instance.finalScore).to.be(expectedValueLiteral);
      });

      it('should have the property screeningScore (base name: "screeningScore")', function() {
        // TODO: update the code to test the property screeningScore
        expect(instance).to.have.property('screeningScore');
        // expect(instance.screeningScore).to.be(expectedValueLiteral);
      });

      it('should have the property initialScore (base name: "initialScore")', function() {
        // TODO: update the code to test the property initialScore
        expect(instance).to.have.property('initialScore');
        // expect(instance.initialScore).to.be(expectedValueLiteral);
      });

      it('should have the property clientSelection (base name: "clientSelection")', function() {
        // TODO: update the code to test the property clientSelection
        expect(instance).to.have.property('clientSelection');
        // expect(instance.clientSelection).to.be(expectedValueLiteral);
      });

      it('should have the property submissionDownloadLink (base name: "submissionDownloadLink")', function() {
        // TODO: update the code to test the property submissionDownloadLink
        expect(instance).to.have.property('submissionDownloadLink');
        // expect(instance.submissionDownloadLink).to.be(expectedValueLiteral);
      });

      it('should have the property previewDownloadLink (base name: "previewDownloadLink")', function() {
        // TODO: update the code to test the property previewDownloadLink
        expect(instance).to.have.property('previewDownloadLink');
        // expect(instance.previewDownloadLink).to.be(expectedValueLiteral);
      });

    });
  });

}));
