/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2002ResultContent', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.InlineResponse2002ResultContent();
      });

      it('should create an instance of InlineResponse2002ResultContent', function() {
        // TODO: update the code to test InlineResponse2002ResultContent
        expect(instance).to.be.a(ApChallengeMicroservice.InlineResponse2002ResultContent);
      });

      it('should have the property oldRating (base name: "oldRating")', function() {
        // TODO: update the code to test the property oldRating
        expect(instance).to.have.property('oldRating');
        // expect(instance.oldRating).to.be(expectedValueLiteral);
      });

      it('should have the property newRating (base name: "newRating")', function() {
        // TODO: update the code to test the property newRating
        expect(instance).to.have.property('newRating');
        // expect(instance.newRating).to.be(expectedValueLiteral);
      });

      it('should have the property finalScore (base name: "finalScore")', function() {
        // TODO: update the code to test the property finalScore
        expect(instance).to.have.property('finalScore');
        // expect(instance.finalScore).to.be(expectedValueLiteral);
      });

      it('should have the property placement (base name: "placement")', function() {
        // TODO: update the code to test the property placement
        expect(instance).to.have.property('placement');
        // expect(instance.placement).to.be(expectedValueLiteral);
      });

      it('should have the property passedReview (base name: "passedReview")', function() {
        // TODO: update the code to test the property passedReview
        expect(instance).to.have.property('passedReview');
        // expect(instance.passedReview).to.be(expectedValueLiteral);
      });

      it('should have the property challengeId (base name: "challengeId")', function() {
        // TODO: update the code to test the property challengeId
        expect(instance).to.have.property('challengeId');
        // expect(instance.challengeId).to.be(expectedValueLiteral);
      });

      it('should have the property userId (base name: "userId")', function() {
        // TODO: update the code to test the property userId
        expect(instance).to.have.property('userId');
        // expect(instance.userId).to.be(expectedValueLiteral);
      });

      it('should have the property handle (base name: "handle")', function() {
        // TODO: update the code to test the property handle
        expect(instance).to.have.property('handle');
        // expect(instance.handle).to.be(expectedValueLiteral);
      });

    });
  });

}));
