/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Phases', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.Phases();
      });

      it('should create an instance of Phases', function() {
        // TODO: update the code to test Phases
        expect(instance).to.be.a(ApChallengeMicroservice.Phases);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property scheduledStartTime (base name: "scheduledStartTime")', function() {
        // TODO: update the code to test the property scheduledStartTime
        expect(instance).to.have.property('scheduledStartTime');
        // expect(instance.scheduledStartTime).to.be(expectedValueLiteral);
      });

      it('should have the property scheduledEndTime (base name: "scheduledEndTime")', function() {
        // TODO: update the code to test the property scheduledEndTime
        expect(instance).to.have.property('scheduledEndTime');
        // expect(instance.scheduledEndTime).to.be(expectedValueLiteral);
      });

      it('should have the property actualStartTime (base name: "actualStartTime")', function() {
        // TODO: update the code to test the property actualStartTime
        expect(instance).to.have.property('actualStartTime');
        // expect(instance.actualStartTime).to.be(expectedValueLiteral);
      });

    });
  });

}));
