/*
 * ap-challenge-microservice
 * Services that provide access and interaction with all sorts of challenges, including design, dev, single round matches, and marathon matches. 
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApChallengeMicroservice);
  }
}(this, function(expect, ApChallengeMicroservice) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ResponseMetadata', function() {
      beforeEach(function() {
        instance = new ApChallengeMicroservice.ResponseMetadata();
      });

      it('should create an instance of ResponseMetadata', function() {
        // TODO: update the code to test ResponseMetadata
        expect(instance).to.be.a(ApChallengeMicroservice.ResponseMetadata);
      });

      it('should have the property totalCount (base name: "totalCount")', function() {
        // TODO: update the code to test the property totalCount
        expect(instance).to.have.property('totalCount');
        // expect(instance.totalCount).to.be(expectedValueLiteral);
      });

      it('should have the property fields (base name: "fields")', function() {
        // TODO: update the code to test the property fields
        expect(instance).to.have.property('fields');
        // expect(instance.fields).to.be(expectedValueLiteral);
      });

    });
  });

}));
